import java.util.ArrayList;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class ShoeTester {
    public static void main(String[] args) {
        ArrayList<Deck> decks = IntStream
            .range(0, 6)
            .mapToObj(i -> new Deck())
            .collect(Collectors.toCollection(ArrayList::new));
        Shoe shoe = new Shoe(decks);
        System.out.println(shoe.toString());
        System.out.println();
        shoe.shuffle();
        System.out.println(shoe.toString());
    }
}

/* TESTER OUTPUT
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds
Two of Spades
Two of Hearts
Two of Clubs
Two of Diamonds
Three of Spades
Three of Hearts
Three of Clubs
Three of Diamonds
Four of Spades
Four of Hearts
Four of Clubs
Four of Diamonds
Five of Spades
Five of Hearts
Five of Clubs
Five of Diamonds
Six of Spades
Six of Hearts
Six of Clubs
Six of Diamonds
Seven of Spades
Seven of Hearts
Seven of Clubs
Seven of Diamonds
Eight of Spades
Eight of Hearts
Eight of Clubs
Eight of Diamonds
Nine of Spades
Nine of Hearts
Nine of Clubs
Nine of Diamonds
Ten of Spades
Ten of Hearts
Ten of Clubs
Ten of Diamonds
Jack of Spades
Jack of Hearts
Jack of Clubs
Jack of Diamonds
Queen of Spades
Queen of Hearts
Queen of Clubs
Queen of Diamonds
King of Spades
King of Hearts
King of Clubs
King of Diamonds
Ace of Spades
Ace of Hearts
Ace of Clubs
Ace of Diamonds

Two of Hearts
Six of Spades
Queen of Hearts
Nine of Clubs
King of Clubs
Six of Spades
Six of Hearts
Three of Spades
Ten of Diamonds
Jack of Clubs
Two of Diamonds
Eight of Clubs
Six of Diamonds
Ten of Clubs
King of Hearts
Nine of Diamonds
Three of Hearts
Ten of Diamonds
Two of Clubs
Jack of Diamonds
Two of Spades
Three of Hearts
Four of Hearts
Two of Clubs
Ace of Clubs
Five of Hearts
Queen of Clubs
Eight of Hearts
Nine of Diamonds
Nine of Hearts
Queen of Diamonds
Six of Hearts
Seven of Hearts
Three of Clubs
King of Hearts
Jack of Hearts
Eight of Spades
Four of Diamonds
Three of Diamonds
King of Spades
King of Hearts
Three of Clubs
Jack of Hearts
Six of Spades
Ten of Diamonds
Queen of Hearts
Queen of Diamonds
Jack of Spades
Jack of Clubs
Ten of Hearts
Three of Diamonds
Nine of Hearts
Eight of Hearts
Five of Diamonds
Nine of Spades
Six of Clubs
Two of Clubs
Four of Diamonds
Queen of Hearts
Three of Diamonds
Four of Clubs
Ace of Diamonds
Six of Diamonds
Ten of Spades
Four of Hearts
Five of Hearts
Four of Diamonds
King of Spades
Jack of Clubs
Ten of Diamonds
Queen of Clubs
Ten of Diamonds
Four of Spades
Nine of Clubs
Five of Clubs
King of Clubs
Three of Diamonds
Nine of Clubs
King of Diamonds
Queen of Diamonds
Ten of Spades
Two of Spades
Nine of Diamonds
Five of Diamonds
Ten of Hearts
Three of Diamonds
Nine of Hearts
Queen of Hearts
Jack of Diamonds
Ace of Spades
Ten of Clubs
Ace of Hearts
Seven of Spades
Queen of Clubs
Nine of Spades
King of Clubs
Ace of Diamonds
Nine of Clubs
Six of Clubs
King of Diamonds
Ten of Clubs
Seven of Spades
King of Spades
Jack of Diamonds
Ace of Spades
Ace of Clubs
Two of Hearts
Seven of Hearts
Seven of Diamonds
Nine of Diamonds
Seven of Diamonds
Ten of Clubs
Eight of Clubs
Three of Hearts
Seven of Spades
Two of Spades
Queen of Clubs
Eight of Spades
Queen of Spades
Five of Clubs
Six of Clubs
Seven of Diamonds
Queen of Hearts
Seven of Clubs
Jack of Clubs
Four of Hearts
Queen of Spades
Ace of Diamonds
Jack of Hearts
Eight of Clubs
Jack of Spades
King of Clubs
Five of Hearts
Seven of Diamonds
Four of Spades
Ace of Diamonds
Five of Hearts
Ace of Diamonds
Seven of Spades
Ace of Clubs
Ten of Spades
Ace of Clubs
Two of Hearts
Queen of Hearts
Four of Clubs
Four of Clubs
Nine of Spades
Three of Clubs
Six of Clubs
Six of Diamonds
Two of Diamonds
Five of Diamonds
Seven of Hearts
Two of Spades
Two of Clubs
Five of Spades
Three of Hearts
Three of Hearts
King of Diamonds
Three of Spades
Jack of Spades
Nine of Hearts
Eight of Diamonds
Ten of Hearts
Jack of Diamonds
Seven of Spades
Seven of Diamonds
Queen of Spades
Two of Diamonds
Eight of Clubs
Jack of Hearts
Two of Hearts
Ace of Clubs
King of Spades
Four of Spades
Eight of Diamonds
Queen of Diamonds
Eight of Hearts
King of Diamonds
Five of Diamonds
Jack of Clubs
Two of Spades
Ten of Spades
Six of Hearts
Five of Hearts
Nine of Spades
Eight of Spades
Six of Spades
Nine of Spades
Ace of Spades
Queen of Clubs
Eight of Spades
Two of Diamonds
Three of Clubs
King of Hearts
Two of Clubs
Ace of Hearts
Seven of Hearts
Eight of Diamonds
Queen of Diamonds
Ace of Clubs
Six of Diamonds
Three of Clubs
Four of Hearts
Eight of Diamonds
Eight of Clubs
Nine of Clubs
Three of Clubs
King of Diamonds
Seven of Diamonds
Six of Spades
Six of Hearts
Nine of Diamonds
Ten of Diamonds
Six of Clubs
Ace of Diamonds
Ten of Hearts
Three of Hearts
Ace of Spades
Five of Clubs
King of Diamonds
Five of Clubs
Seven of Hearts
Two of Hearts
Four of Diamonds
Four of Diamonds
Seven of Hearts
Nine of Spades
Ace of Spades
Queen of Diamonds
Two of Clubs
Five of Clubs
Six of Spades
Ace of Hearts
Five of Clubs
Ten of Hearts
Ace of Spades
Three of Spades
Eight of Hearts
Seven of Clubs
Four of Diamonds
King of Spades
Ace of Hearts
Jack of Diamonds
Eight of Diamonds
Six of Diamonds
Three of Spades
King of Clubs
Three of Diamonds
King of Hearts
Seven of Clubs
Six of Diamonds
Six of Hearts
Five of Diamonds
Five of Spades
Queen of Spades
Jack of Diamonds
Four of Spades
Two of Diamonds
Jack of Spades
Ten of Spades
Two of Diamonds
Ten of Hearts
Eight of Spades
Eight of Diamonds
Four of Clubs
Jack of Spades
Nine of Diamonds
Jack of Hearts
Ten of Clubs
Five of Spades
Five of Spades
Five of Spades
Seven of Spades
Queen of Clubs
Queen of Spades
Four of Clubs
Six of Clubs
Eight of Clubs
Four of Clubs
Nine of Hearts
Two of Spades
Jack of Spades
King of Spades
Four of Spades
Jack of Hearts
Nine of Clubs
Ten of Spades
Queen of Spades
Ace of Hearts
Four of Hearts
Seven of Clubs
Five of Hearts
Ace of Hearts
Eight of Hearts
Seven of Clubs
Six of Hearts
Ten of Clubs
Five of Diamonds
Two of Hearts
Jack of Clubs
Seven of Clubs
Nine of Hearts
Four of Spades
Eight of Spades
King of Clubs
Three of Spades
Eight of Hearts
Four of Hearts
King of Hearts
Three of Spades
Five of Spades
 */
